/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_personal_todo_personalTodo_create_parameter_0$schema = z.object({
  'title': z.string().readonly(),
  'notes': z.union([z.undefined(), z.literal(null), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("pending"), z.literal("in_progress"), z.literal("completed")]).readonly().optional(),
  'priority': z.union([z.undefined(), z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly().optional(),
  'dueAt': z.union([z.undefined(), z.literal(null), z.string()]).readonly().optional(),
  'tags': z.union([z.undefined(), z.array(z.string())]).readonly().optional(),
})
const dsh_personal_todo_personalTodo_create_result$schema = z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("completed")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_personal_todo_personalTodo_delete_parameter_0$schema = z.object({
  'id': z.string().readonly(),
})
const dsh_personal_todo_personalTodo_delete_result$schema = z.object({
  'id': z.string().readonly(),
  'deleted': z.literal(true).readonly(),
})
const dsh_personal_todo_personalTodo_list_parameter_0$schema = z.object({
  'statuses': z.union([z.undefined(), z.array(z.union([z.literal("pending"), z.literal("in_progress"), z.literal("completed")]))]).readonly().optional(),
  'priorities': z.union([z.undefined(), z.array(z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]))]).readonly().optional(),
  'tags': z.union([z.undefined(), z.array(z.string())]).readonly().optional(),
  'dueBefore': z.union([z.undefined(), z.string()]).readonly().optional(),
  'search': z.union([z.undefined(), z.string()]).readonly().optional(),
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
  'offset': z.union([z.undefined(), z.number()]).readonly().optional(),
})
const dsh_personal_todo_personalTodo_list_result$schema = z.object({
  'todos': z.array(z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("completed")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
})).readonly(),
  'total': z.number().readonly(),
  'counts': z.object({
  'pending': z.number().readonly(),
  'inProgress': z.number().readonly(),
  'completed': z.number().readonly(),
}).readonly(),
  'hasMore': z.boolean().readonly(),
})
const dsh_personal_todo_personalTodo_update_parameter_0$schema = z.object({
  'id': z.string().readonly(),
  'patch': z.object({
  'title': z.union([z.undefined(), z.string()]).readonly().optional(),
  'notes': z.union([z.undefined(), z.literal(null), z.string()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("pending"), z.literal("in_progress"), z.literal("completed")]).readonly().optional(),
  'priority': z.union([z.undefined(), z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly().optional(),
  'dueAt': z.union([z.undefined(), z.literal(null), z.string()]).readonly().optional(),
  'tags': z.union([z.undefined(), z.array(z.string())]).readonly().optional(),
}).readonly(),
})
const dsh_personal_todo_personalTodo_update_result$schema = z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("completed")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
})

export const TYPERT = {
  package: 'dsh-personal-todo',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-personal-todo#personalTodo/create',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#CreateTodoInput',
            schema: dsh_personal_todo_personalTodo_create_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#Todo',
        schema: dsh_personal_todo_personalTodo_create_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":84,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/delete',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#DeleteTodoRequest',
            schema: dsh_personal_todo_personalTodo_delete_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#DeleteTodoResult',
        schema: dsh_personal_todo_personalTodo_delete_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":98,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/list',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#ListTodoInput',
            schema: dsh_personal_todo_personalTodo_list_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#TodoListResult',
        schema: dsh_personal_todo_personalTodo_list_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":77,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/update',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'update',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#UpdateTodoRequest',
            schema: dsh_personal_todo_personalTodo_update_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#Todo',
        schema: dsh_personal_todo_personalTodo_update_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":91,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Authoritative todo service shared by generated Remote methods and Agent tools.",
        "summary": "Authoritative todo service shared by generated Remote methods and Agent tools.",
        "tags": [],
        "jsDoc": "/** Authoritative todo service shared by generated Remote methods and Agent tools. */",
        "key": "personalTodo",
        "exportName": "PersonalTodoService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote list(request: ListTodoInput, signal: AbortSignal): Promise<TodoListResult>",
            "summary": "List one bounded page.",
            "jsDoc": "/** List one bounded page. Cancellation is checked before synchronous SQLite work begins. */"
          },
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote create(request: CreateTodoInput, signal: AbortSignal): Promise<Todo>",
            "summary": "Create one durable todo.",
            "jsDoc": "/** Create one durable todo. */"
          },
          {
            "kind": "method",
            "name": "update",
            "signature": "@Remote update(request: UpdateTodoRequest, signal: AbortSignal): Promise<Todo>",
            "summary": "Update one durable todo.",
            "jsDoc": "/** Update one durable todo. */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote delete(request: DeleteTodoRequest, signal: AbortSignal): Promise<DeleteTodoResult>",
            "summary": "Permanently delete one todo.",
            "jsDoc": "/** Permanently delete one todo. */"
          }
        ],
        "types": [
          {
            "name": "CreateTodoInput",
            "declaration": "export interface CreateTodoInput {\n    readonly title: string;\n    readonly notes?: string | null;\n    readonly status?: TodoStatus;\n    readonly priority?: TodoPriority;\n    readonly dueAt?: string | null;\n    readonly tags?: readonly string[];\n}"
          },
          {
            "name": "DeleteTodoRequest",
            "declaration": "export interface DeleteTodoRequest {\n    readonly id: string;\n}"
          },
          {
            "name": "DeleteTodoResult",
            "declaration": "export interface DeleteTodoResult {\n    readonly id: string;\n    readonly deleted: true;\n}"
          },
          {
            "name": "ListTodoInput",
            "declaration": "export interface ListTodoInput {\n    readonly statuses?: readonly TodoStatus[];\n    readonly priorities?: readonly TodoPriority[];\n    readonly tags?: readonly string[];\n    readonly dueBefore?: string;\n    readonly search?: string;\n    readonly limit?: number;\n    readonly offset?: number;\n}"
          },
          {
            "name": "Todo",
            "declaration": "export interface Todo {\n    readonly id: string;\n    readonly title: string;\n    readonly notes: string | null;\n    readonly status: TodoStatus;\n    readonly priority: TodoPriority;\n    readonly dueAt: string | null;\n    readonly tags: string[];\n    readonly createdAt: string;\n    readonly updatedAt: string;\n    readonly completedAt: string | null;\n}"
          },
          {
            "name": "TodoCounts",
            "declaration": "export interface TodoCounts {\n    readonly pending: number;\n    readonly inProgress: number;\n    readonly completed: number;\n}"
          },
          {
            "name": "TodoListResult",
            "declaration": "export interface TodoListResult {\n    readonly todos: Todo[];\n    readonly total: number;\n    readonly counts: TodoCounts;\n    readonly hasMore: boolean;\n}"
          },
          {
            "name": "TodoPriority",
            "declaration": "export type TodoPriority = (typeof TODO_PRIORITIES)[number];"
          },
          {
            "name": "TodoStatus",
            "declaration": "export type TodoStatus = (typeof TODO_STATUSES)[number];"
          },
          {
            "name": "UpdateTodoPatch",
            "declaration": "export interface UpdateTodoPatch {\n    readonly title?: string;\n    readonly notes?: string | null;\n    readonly status?: TodoStatus;\n    readonly priority?: TodoPriority;\n    readonly dueAt?: string | null;\n    readonly tags?: readonly string[];\n}"
          },
          {
            "name": "UpdateTodoRequest",
            "declaration": "export interface UpdateTodoRequest {\n    readonly id: string;\n    readonly patch: UpdateTodoPatch;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
