/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_personal_todo_personalTodo_approve_parameter_0$schema = z.object({
  'id': z.string().readonly(),
})
const dsh_personal_todo_personalTodo_approve_result$schema = z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'assignee': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("blocked"), z.literal("in_review"), z.literal("completed"), z.literal("cancelled")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'primarySessionId': z.union([z.literal(null), z.string()]).readonly(),
  'activeRunId': z.union([z.literal(null), z.string()]).readonly(),
  'latestSummary': z.union([z.literal(null), z.string()]).readonly(),
  'blockedReason': z.union([z.literal(null), z.string()]).readonly(),
  'reviewRound': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_personal_todo_personalTodo_archive_parameter_0$schema = z.object({
  'id': z.string().readonly(),
})
const dsh_personal_todo_personalTodo_archive_result$schema = z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'assignee': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("blocked"), z.literal("in_review"), z.literal("completed"), z.literal("cancelled")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'primarySessionId': z.union([z.literal(null), z.string()]).readonly(),
  'activeRunId': z.union([z.literal(null), z.string()]).readonly(),
  'latestSummary': z.union([z.literal(null), z.string()]).readonly(),
  'blockedReason': z.union([z.literal(null), z.string()]).readonly(),
  'reviewRound': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_personal_todo_personalTodo_create_parameter_0$schema = z.object({
  'title': z.string().readonly(),
  'notes': z.union([z.undefined(), z.literal(null), z.string()]).readonly().optional(),
  'assignee': z.union([z.undefined(), z.literal(null), z.string()]).readonly().optional(),
  'priority': z.union([z.undefined(), z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly().optional(),
  'dueAt': z.union([z.undefined(), z.literal(null), z.string()]).readonly().optional(),
  'tags': z.union([z.undefined(), z.array(z.string())]).readonly().optional(),
})
const dsh_personal_todo_personalTodo_create_result$schema = z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'assignee': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("blocked"), z.literal("in_review"), z.literal("completed"), z.literal("cancelled")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'primarySessionId': z.union([z.literal(null), z.string()]).readonly(),
  'activeRunId': z.union([z.literal(null), z.string()]).readonly(),
  'latestSummary': z.union([z.literal(null), z.string()]).readonly(),
  'blockedReason': z.union([z.literal(null), z.string()]).readonly(),
  'reviewRound': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_personal_todo_personalTodo_delete_parameter_0$schema = z.object({
  'id': z.string().readonly(),
})
const dsh_personal_todo_personalTodo_delete_result$schema = z.object({
  'id': z.string().readonly(),
  'deleted': z.literal(true).readonly(),
})
const dsh_personal_todo_personalTodo_exportData_parameter_0$schema = z.record(z.string(), z.never())
const dsh_personal_todo_personalTodo_exportData_result$schema = z.object({
  'filename': z.string().readonly(),
  'json': z.string().readonly(),
})
const dsh_personal_todo_personalTodo_get_parameter_0$schema = z.object({
  'id': z.string().readonly(),
})
const dsh_personal_todo_personalTodo_get_result$schema = z.object({
  'todo': z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'assignee': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("blocked"), z.literal("in_review"), z.literal("completed"), z.literal("cancelled")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'primarySessionId': z.union([z.literal(null), z.string()]).readonly(),
  'activeRunId': z.union([z.literal(null), z.string()]).readonly(),
  'latestSummary': z.union([z.literal(null), z.string()]).readonly(),
  'blockedReason': z.union([z.literal(null), z.string()]).readonly(),
  'reviewRound': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
}).readonly(),
  'runs': z.array(z.object({
  'id': z.string().readonly(),
  'todoId': z.string().readonly(),
  'sequence': z.number().readonly(),
  'status': z.union([z.literal("cancelled"), z.literal("running"), z.literal("waiting_input"), z.literal("submitted"), z.literal("failed")]).readonly(),
  'rootSessionId': z.string().readonly(),
  'resultSummary': z.union([z.literal(null), z.string()]).readonly(),
  'verification': z.union([z.literal(null), z.string()]).readonly(),
  'risk': z.union([z.literal(null), z.string()]).readonly(),
  'startedAt': z.string().readonly(),
  'finishedAt': z.union([z.literal(null), z.string()]).readonly(),
})).readonly(),
  'sessions': z.array(z.object({
  'todoId': z.string().readonly(),
  'sessionId': z.string().readonly(),
  'role': z.union([z.literal("primary"), z.literal("related")]).readonly(),
  'parentSessionId': z.union([z.literal(null), z.string()]).readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
  'events': z.array(z.object({
  'id': z.string().readonly(),
  'todoId': z.string().readonly(),
  'runId': z.union([z.literal(null), z.string()]).readonly(),
  'type': z.union([z.literal("blocked"), z.literal("cancelled"), z.literal("created"), z.literal("updated"), z.literal("run_started"), z.literal("progress"), z.literal("user_replied"), z.literal("review_submitted"), z.literal("review_approved"), z.literal("changes_requested"), z.literal("run_failed"), z.literal("archived"), z.literal("restored")]).readonly(),
  'message': z.union([z.literal(null), z.string()]).readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
})
const dsh_personal_todo_personalTodo_importData_parameter_0$schema = z.object({
  'json': z.string().readonly(),
})
const dsh_personal_todo_personalTodo_importData_result$schema = z.object({
  'imported': z.number().readonly(),
  'skipped': z.number().readonly(),
  'resetToPending': z.number().readonly(),
})
const dsh_personal_todo_personalTodo_list_parameter_0$schema = z.object({
  'statuses': z.union([z.undefined(), z.array(z.union([z.literal("pending"), z.literal("in_progress"), z.literal("blocked"), z.literal("in_review"), z.literal("completed"), z.literal("cancelled")]))]).readonly().optional(),
  'priorities': z.union([z.undefined(), z.array(z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]))]).readonly().optional(),
  'tags': z.union([z.undefined(), z.array(z.string())]).readonly().optional(),
  'dueBefore': z.union([z.undefined(), z.string()]).readonly().optional(),
  'search': z.union([z.undefined(), z.string()]).readonly().optional(),
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
  'offset': z.union([z.undefined(), z.number()]).readonly().optional(),
  'archived': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_personal_todo_personalTodo_list_result$schema = z.object({
  'todos': z.array(z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'assignee': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("blocked"), z.literal("in_review"), z.literal("completed"), z.literal("cancelled")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'primarySessionId': z.union([z.literal(null), z.string()]).readonly(),
  'activeRunId': z.union([z.literal(null), z.string()]).readonly(),
  'latestSummary': z.union([z.literal(null), z.string()]).readonly(),
  'blockedReason': z.union([z.literal(null), z.string()]).readonly(),
  'reviewRound': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
})).readonly(),
  'total': z.number().readonly(),
  'counts': z.object({
  'pending': z.number().readonly(),
  'inProgress': z.number().readonly(),
  'blocked': z.number().readonly(),
  'inReview': z.number().readonly(),
  'completed': z.number().readonly(),
  'cancelled': z.number().readonly(),
  'archived': z.number().readonly(),
}).readonly(),
  'hasMore': z.boolean().readonly(),
})
const dsh_personal_todo_personalTodo_reply_parameter_0$schema = z.object({
  'message': z.string().readonly(),
  'id': z.string().readonly(),
})
const dsh_personal_todo_personalTodo_reply_result$schema = z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'assignee': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("blocked"), z.literal("in_review"), z.literal("completed"), z.literal("cancelled")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'primarySessionId': z.union([z.literal(null), z.string()]).readonly(),
  'activeRunId': z.union([z.literal(null), z.string()]).readonly(),
  'latestSummary': z.union([z.literal(null), z.string()]).readonly(),
  'blockedReason': z.union([z.literal(null), z.string()]).readonly(),
  'reviewRound': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_personal_todo_personalTodo_requestChanges_parameter_0$schema = z.object({
  'feedback': z.string().readonly(),
  'id': z.string().readonly(),
})
const dsh_personal_todo_personalTodo_requestChanges_result$schema = z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'assignee': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("blocked"), z.literal("in_review"), z.literal("completed"), z.literal("cancelled")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'primarySessionId': z.union([z.literal(null), z.string()]).readonly(),
  'activeRunId': z.union([z.literal(null), z.string()]).readonly(),
  'latestSummary': z.union([z.literal(null), z.string()]).readonly(),
  'blockedReason': z.union([z.literal(null), z.string()]).readonly(),
  'reviewRound': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_personal_todo_personalTodo_restore_parameter_0$schema = z.object({
  'id': z.string().readonly(),
})
const dsh_personal_todo_personalTodo_restore_result$schema = z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'assignee': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("blocked"), z.literal("in_review"), z.literal("completed"), z.literal("cancelled")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'primarySessionId': z.union([z.literal(null), z.string()]).readonly(),
  'activeRunId': z.union([z.literal(null), z.string()]).readonly(),
  'latestSummary': z.union([z.literal(null), z.string()]).readonly(),
  'blockedReason': z.union([z.literal(null), z.string()]).readonly(),
  'reviewRound': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_personal_todo_personalTodo_start_parameter_0$schema = z.object({
  'id': z.string().readonly(),
})
const dsh_personal_todo_personalTodo_start_result$schema = z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'assignee': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("blocked"), z.literal("in_review"), z.literal("completed"), z.literal("cancelled")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'primarySessionId': z.union([z.literal(null), z.string()]).readonly(),
  'activeRunId': z.union([z.literal(null), z.string()]).readonly(),
  'latestSummary': z.union([z.literal(null), z.string()]).readonly(),
  'blockedReason': z.union([z.literal(null), z.string()]).readonly(),
  'reviewRound': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_personal_todo_personalTodo_update_parameter_0$schema = z.object({
  'id': z.string().readonly(),
  'patch': z.object({
  'title': z.union([z.undefined(), z.string()]).readonly().optional(),
  'notes': z.union([z.undefined(), z.literal(null), z.string()]).readonly().optional(),
  'assignee': z.union([z.undefined(), z.literal(null), z.string()]).readonly().optional(),
  'priority': z.union([z.undefined(), z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly().optional(),
  'dueAt': z.union([z.undefined(), z.literal(null), z.string()]).readonly().optional(),
  'tags': z.union([z.undefined(), z.array(z.string())]).readonly().optional(),
}).readonly(),
})
const dsh_personal_todo_personalTodo_update_result$schema = z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'notes': z.union([z.literal(null), z.string()]).readonly(),
  'assignee': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("pending"), z.literal("in_progress"), z.literal("blocked"), z.literal("in_review"), z.literal("completed"), z.literal("cancelled")]).readonly(),
  'priority': z.union([z.literal("none"), z.literal("low"), z.literal("medium"), z.literal("high")]).readonly(),
  'dueAt': z.union([z.literal(null), z.string()]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'primarySessionId': z.union([z.literal(null), z.string()]).readonly(),
  'activeRunId': z.union([z.literal(null), z.string()]).readonly(),
  'latestSummary': z.union([z.literal(null), z.string()]).readonly(),
  'blockedReason': z.union([z.literal(null), z.string()]).readonly(),
  'reviewRound': z.number().readonly(),
  'revision': z.number().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'completedAt': z.union([z.literal(null), z.string()]).readonly(),
  'archivedAt': z.union([z.literal(null), z.string()]).readonly(),
})

export const TYPERT = {
  package: 'dsh-personal-todo',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-personal-todo#personalTodo/approve',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'approve',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#TodoIdRequest',
            schema: dsh_personal_todo_personalTodo_approve_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#Todo',
        schema: dsh_personal_todo_personalTodo_approve_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":166,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/archive',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'archive',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#TodoIdRequest',
            schema: dsh_personal_todo_personalTodo_archive_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#Todo',
        schema: dsh_personal_todo_personalTodo_archive_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":173,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/create',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'create',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#CreateTodoInput',
            schema: dsh_personal_todo_personalTodo_create_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#Todo',
        schema: dsh_personal_todo_personalTodo_create_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":131,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/delete',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#DeleteTodoRequest',
            schema: dsh_personal_todo_personalTodo_delete_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#DeleteTodoResult',
        schema: dsh_personal_todo_personalTodo_delete_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":209,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/exportData',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'exportData',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_request',
          wire: '_request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#ExportTodoDataRequest',
            schema: dsh_personal_todo_personalTodo_exportData_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#ExportTodoDataResult',
        schema: dsh_personal_todo_personalTodo_exportData_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":118,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/get',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'get',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#TodoIdRequest',
            schema: dsh_personal_todo_personalTodo_get_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#TodoDetail',
        schema: dsh_personal_todo_personalTodo_get_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":138,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/importData',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'importData',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#ImportTodoDataRequest',
            schema: dsh_personal_todo_personalTodo_importData_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#ImportTodoDataResult',
        schema: dsh_personal_todo_personalTodo_importData_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":124,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/list',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#ListTodoInput',
            schema: dsh_personal_todo_personalTodo_list_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#TodoListResult',
        schema: dsh_personal_todo_personalTodo_list_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":112,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/reply',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'reply',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#ReplyTodoRequest',
            schema: dsh_personal_todo_personalTodo_reply_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#Todo',
        schema: dsh_personal_todo_personalTodo_reply_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":159,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/requestChanges',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'requestChanges',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#RequestTodoChangesRequest',
            schema: dsh_personal_todo_personalTodo_requestChanges_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#Todo',
        schema: dsh_personal_todo_personalTodo_requestChanges_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":187,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/restore',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'restore',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#TodoIdRequest',
            schema: dsh_personal_todo_personalTodo_restore_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#Todo',
        schema: dsh_personal_todo_personalTodo_restore_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":180,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/start',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'start',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#TodoIdRequest',
            schema: dsh_personal_todo_personalTodo_start_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#Todo',
        schema: dsh_personal_todo_personalTodo_start_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":152,"column":3},
    },
    {
      id: 'dsh-personal-todo#personalTodo/update',
      service: 'personalTodo',
      namespace: 'personalTodo',
      method: 'update',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-personal-todo/types#UpdateTodoRequest',
            schema: dsh_personal_todo_personalTodo_update_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-personal-todo/types#Todo',
        schema: dsh_personal_todo_personalTodo_update_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-personal-todo/src/index.ts","line":145,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "生成的 Remote 方法与 Agent 工具共用的权威待办服务。",
        "summary": "生成的 Remote 方法与 Agent 工具共用的权威待办服务。",
        "tags": [],
        "jsDoc": "/** 生成的 Remote 方法与 Agent 工具共用的权威待办服务。 */",
        "key": "personalTodo",
        "exportName": "PersonalTodoService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote list(request: ListTodoInput, signal: AbortSignal): Promise<TodoListResult>",
            "summary": "查询一页待办；在开始同步 SQLite 操作前检查取消信号。",
            "jsDoc": "/** 查询一页待办；在开始同步 SQLite 操作前检查取消信号。 */"
          },
          {
            "kind": "method",
            "name": "exportData",
            "signature": "@Remote exportData(_request: ExportTodoDataRequest, signal: AbortSignal): Promise<ExportTodoDataResult>"
          },
          {
            "kind": "method",
            "name": "importData",
            "signature": "@Remote importData(request: ImportTodoDataRequest, signal: AbortSignal): Promise<ImportTodoDataResult>"
          },
          {
            "kind": "method",
            "name": "create",
            "signature": "@Remote create(request: CreateTodoInput, signal: AbortSignal): Promise<Todo>",
            "summary": "创建并持久化一条待办。",
            "jsDoc": "/** 创建并持久化一条待办。 */"
          },
          {
            "kind": "method",
            "name": "get",
            "signature": "@Remote get(request: TodoIdRequest, signal: AbortSignal): Promise<TodoDetail>",
            "summary": "读取待办及其执行轮次、关联会话和活动记录。",
            "jsDoc": "/** 读取待办及其执行轮次、关联会话和活动记录。 */"
          },
          {
            "kind": "method",
            "name": "update",
            "signature": "@Remote update(request: UpdateTodoRequest, signal: AbortSignal): Promise<Todo>",
            "summary": "更新已持久化的待办。",
            "jsDoc": "/** 更新已持久化的待办。 */"
          },
          {
            "kind": "method",
            "name": "start",
            "signature": "@Remote start(request: TodoIdRequest, signal: AbortSignal): Promise<Todo>",
            "summary": "在待办的持久化根会话中启动一条待处理任务。",
            "jsDoc": "/** 在待办的持久化根会话中启动一条待处理任务。 */"
          },
          {
            "kind": "method",
            "name": "reply",
            "signature": "@Remote reply(request: ReplyTodoRequest, signal: AbortSignal): Promise<Todo>",
            "summary": "使用用户回复继续执行被阻塞的待办。",
            "jsDoc": "/** 使用用户回复继续执行被阻塞的待办。 */"
          },
          {
            "kind": "method",
            "name": "approve",
            "signature": "@Remote approve(request: TodoIdRequest, signal: AbortSignal): Promise<Todo>",
            "summary": "用户完成待处理、执行中、阻塞或待审核的待办；保留历史，不中断 Agent。",
            "jsDoc": "/** 用户完成待处理、执行中、阻塞或待审核的待办；保留历史，不中断 Agent。 */"
          },
          {
            "kind": "method",
            "name": "archive",
            "signature": "@Remote archive(request: TodoIdRequest, signal: AbortSignal): Promise<Todo>",
            "summary": "归档待办，不改变其生命周期状态。",
            "jsDoc": "/** 归档待办，不改变其生命周期状态。 */"
          },
          {
            "kind": "method",
            "name": "restore",
            "signature": "@Remote restore(request: TodoIdRequest, signal: AbortSignal): Promise<Todo>",
            "summary": "将归档待办恢复到对应生命周期列表。",
            "jsDoc": "/** 将归档待办恢复到对应生命周期列表。 */"
          },
          {
            "kind": "method",
            "name": "requestChanges",
            "signature": "@Remote requestChanges(request: RequestTodoChangesRequest, signal: AbortSignal): Promise<Todo>",
            "summary": "将用户修改意见发回待办的根会话。",
            "jsDoc": "/** 将用户修改意见发回待办的根会话。 */"
          },
          {
            "kind": "method",
            "name": "reportProgress",
            "signature": "reportProgress(request: ReportTodoProgressRequest, sessionId: string): Promise<Todo>",
            "summary": "记录待办主 Agent 会话汇报的进度节点。",
            "jsDoc": "/** 记录待办主 Agent 会话汇报的进度节点。 */"
          },
          {
            "kind": "method",
            "name": "block",
            "signature": "block(request: BlockTodoRequest, sessionId: string): Promise<Todo>",
            "summary": "根据主 Agent 会话提出的问题暂停待办。",
            "jsDoc": "/** 根据主 Agent 会话提出的问题暂停待办。 */"
          },
          {
            "kind": "method",
            "name": "submitReview",
            "signature": "submitReview(request: SubmitTodoReviewRequest, sessionId: string): Promise<Todo>",
            "summary": "提交主 Agent 会话的执行结果，等待用户审核。",
            "jsDoc": "/** 提交主 Agent 会话的执行结果，等待用户审核。 */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote delete(request: DeleteTodoRequest, signal: AbortSignal): Promise<DeleteTodoResult>",
            "summary": "永久删除一条待办。",
            "jsDoc": "/** 永久删除一条待办。 */"
          }
        ],
        "types": [
          {
            "name": "BlockTodoRequest",
            "declaration": "export interface BlockTodoRequest extends TodoIdRequest {\n    readonly question: string;\n}"
          },
          {
            "name": "CreateTodoInput",
            "declaration": "export interface CreateTodoInput {\n    readonly title: string;\n    readonly notes?: string | null;\n    readonly assignee?: string | null;\n    readonly priority?: TodoPriority;\n    readonly dueAt?: string | null;\n    readonly tags?: readonly string[];\n}"
          },
          {
            "name": "DeleteTodoRequest",
            "declaration": "export type DeleteTodoRequest = TodoIdRequest;"
          },
          {
            "name": "DeleteTodoResult",
            "declaration": "export interface DeleteTodoResult {\n    readonly id: string;\n    readonly deleted: true;\n}"
          },
          {
            "name": "ExportTodoDataRequest",
            "declaration": "export type ExportTodoDataRequest = Record<string, never>;"
          },
          {
            "name": "ExportTodoDataResult",
            "declaration": "export interface ExportTodoDataResult {\n    readonly filename: string;\n    readonly json: string;\n}"
          },
          {
            "name": "ImportTodoDataRequest",
            "declaration": "export interface ImportTodoDataRequest {\n    readonly json: string;\n}"
          },
          {
            "name": "ImportTodoDataResult",
            "declaration": "export interface ImportTodoDataResult {\n    readonly imported: number;\n    readonly skipped: number;\n    readonly resetToPending: number;\n}"
          },
          {
            "name": "ListTodoInput",
            "declaration": "export interface ListTodoInput {\n    readonly statuses?: readonly TodoStatus[];\n    readonly priorities?: readonly TodoPriority[];\n    readonly tags?: readonly string[];\n    readonly dueBefore?: string;\n    readonly search?: string;\n    readonly limit?: number;\n    readonly offset?: number;\n    readonly archived?: boolean;\n}"
          },
          {
            "name": "ReplyTodoRequest",
            "declaration": "export interface ReplyTodoRequest extends TodoIdRequest {\n    readonly message: string;\n}"
          },
          {
            "name": "ReportTodoProgressRequest",
            "declaration": "export interface ReportTodoProgressRequest extends TodoIdRequest {\n    readonly message: string;\n}"
          },
          {
            "name": "RequestTodoChangesRequest",
            "declaration": "export interface RequestTodoChangesRequest extends TodoIdRequest {\n    readonly feedback: string;\n}"
          },
          {
            "name": "SubmitTodoReviewRequest",
            "declaration": "export interface SubmitTodoReviewRequest extends TodoIdRequest {\n    readonly summary: string;\n    readonly verification?: string | null;\n    readonly risk?: string | null;\n}"
          },
          {
            "name": "Todo",
            "declaration": "export interface Todo {\n    readonly id: string;\n    readonly title: string;\n    readonly notes: string | null;\n    readonly assignee: string | null;\n    readonly status: TodoStatus;\n    readonly priority: TodoPriority;\n    readonly dueAt: string | null;\n    readonly tags: string[];\n    readonly primarySessionId: string | null;\n    readonly activeRunId: string | null;\n    readonly latestSummary: string | null;\n    readonly blockedReason: string | null;\n    readonly reviewRound: number;\n    readonly revision: number;\n    readonly createdAt: string;\n    readonly updatedAt: string;\n    readonly completedAt: string | null;\n    readonly archivedAt: string | null;\n}"
          },
          {
            "name": "TodoCounts",
            "declaration": "export interface TodoCounts {\n    readonly pending: number;\n    readonly inProgress: number;\n    readonly blocked: number;\n    readonly inReview: number;\n    readonly completed: number;\n    readonly cancelled: number;\n    readonly archived: number;\n}"
          },
          {
            "name": "TodoDetail",
            "declaration": "export interface TodoDetail {\n    readonly todo: Todo;\n    readonly runs: TodoRun[];\n    readonly sessions: TodoSession[];\n    readonly events: TodoEvent[];\n}"
          },
          {
            "name": "TodoEvent",
            "declaration": "export interface TodoEvent {\n    readonly id: string;\n    readonly todoId: string;\n    readonly runId: string | null;\n    readonly type: TodoEventType;\n    readonly message: string | null;\n    readonly createdAt: string;\n}"
          },
          {
            "name": "TodoEventType",
            "declaration": "export type TodoEventType = (typeof TODO_EVENT_TYPES)[number];"
          },
          {
            "name": "TodoIdRequest",
            "declaration": "export interface TodoIdRequest {\n    readonly id: string;\n}"
          },
          {
            "name": "TodoListResult",
            "declaration": "export interface TodoListResult {\n    readonly todos: Todo[];\n    readonly total: number;\n    readonly counts: TodoCounts;\n    readonly hasMore: boolean;\n}"
          },
          {
            "name": "TodoPriority",
            "declaration": "export type TodoPriority = (typeof TODO_PRIORITIES)[number];"
          },
          {
            "name": "TodoRun",
            "declaration": "export interface TodoRun {\n    readonly id: string;\n    readonly todoId: string;\n    readonly sequence: number;\n    readonly status: TodoRunStatus;\n    readonly rootSessionId: string;\n    readonly resultSummary: string | null;\n    readonly verification: string | null;\n    readonly risk: string | null;\n    readonly startedAt: string;\n    readonly finishedAt: string | null;\n}"
          },
          {
            "name": "TodoRunStatus",
            "declaration": "export type TodoRunStatus = (typeof TODO_RUN_STATUSES)[number];"
          },
          {
            "name": "TodoSession",
            "declaration": "export interface TodoSession {\n    readonly todoId: string;\n    readonly sessionId: string;\n    readonly role: 'primary' | 'related';\n    readonly parentSessionId: string | null;\n    readonly createdAt: string;\n}"
          },
          {
            "name": "TodoStatus",
            "declaration": "export type TodoStatus = (typeof TODO_STATUSES)[number];"
          },
          {
            "name": "UpdateTodoPatch",
            "declaration": "export interface UpdateTodoPatch {\n    readonly title?: string;\n    readonly notes?: string | null;\n    readonly assignee?: string | null;\n    readonly priority?: TodoPriority;\n    readonly dueAt?: string | null;\n    readonly tags?: readonly string[];\n}"
          },
          {
            "name": "UpdateTodoRequest",
            "declaration": "export interface UpdateTodoRequest {\n    readonly id: string;\n    readonly patch: UpdateTodoPatch;\n}"
          }
        ]
      }
    ],
    "events": [
      {
        "tags": [
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/** @mode emit */",
        "name": "session/created",
        "mode": "emit",
        "signature": "'session/created'(session: { readonly id: string; readonly header: { readonly parentSession?: string; }; }): void"
      }
    ],
    "objects": []
  },
}
