/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CreateTodoInput, DeleteTodoRequest, DeleteTodoResult, ExportTodoDataRequest, ExportTodoDataResult, ImportTodoDataRequest, ImportTodoDataResult, ListTodoInput, ReplyTodoRequest, RequestTodoChangesRequest, SetTodoStatusRequest, Todo, TodoDetail, TodoIdRequest, TodoListResult, UpdateTodoRequest } from 'dsh-personal-todo/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$706572736f6e616c546f646f {
    approve: (request: TodoIdRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    archive: (request: TodoIdRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    create: (request: CreateTodoInput, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    delete: (request: DeleteTodoRequest, signal?: AbortSignal) => Promise<RemoteResult<DeleteTodoResult>>
    exportData: (_request: ExportTodoDataRequest, signal?: AbortSignal) => Promise<RemoteResult<ExportTodoDataResult>>
    get: (request: TodoIdRequest, signal?: AbortSignal) => Promise<RemoteResult<TodoDetail>>
    importData: (request: ImportTodoDataRequest, signal?: AbortSignal) => Promise<RemoteResult<ImportTodoDataResult>>
    list: (request: ListTodoInput, signal?: AbortSignal) => Promise<RemoteResult<TodoListResult>>
    reply: (request: ReplyTodoRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    requestChanges: (request: RequestTodoChangesRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    restore: (request: TodoIdRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    setStatus: (request: SetTodoStatusRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    start: (request: TodoIdRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    stop: (request: TodoIdRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    update: (request: UpdateTodoRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
  }
  interface TypertRemoteMap {
    'personalTodo/approve': (request: TodoIdRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    'personalTodo/archive': (request: TodoIdRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    'personalTodo/create': (request: CreateTodoInput, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    'personalTodo/delete': (request: DeleteTodoRequest, signal?: AbortSignal) => Promise<RemoteResult<DeleteTodoResult>>
    'personalTodo/exportData': (_request: ExportTodoDataRequest, signal?: AbortSignal) => Promise<RemoteResult<ExportTodoDataResult>>
    'personalTodo/get': (request: TodoIdRequest, signal?: AbortSignal) => Promise<RemoteResult<TodoDetail>>
    'personalTodo/importData': (request: ImportTodoDataRequest, signal?: AbortSignal) => Promise<RemoteResult<ImportTodoDataResult>>
    'personalTodo/list': (request: ListTodoInput, signal?: AbortSignal) => Promise<RemoteResult<TodoListResult>>
    'personalTodo/reply': (request: ReplyTodoRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    'personalTodo/requestChanges': (request: RequestTodoChangesRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    'personalTodo/restore': (request: TodoIdRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    'personalTodo/setStatus': (request: SetTodoStatusRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    'personalTodo/start': (request: TodoIdRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    'personalTodo/stop': (request: TodoIdRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
    'personalTodo/update': (request: UpdateTodoRequest, signal?: AbortSignal) => Promise<RemoteResult<Todo>>
  }
  interface TypertRemoteNamespaceMap {
    'personalTodo': TypertRemoteNamespace$706572736f6e616c546f646f
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
